version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-oportunidades-cefet
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: oportunidadescefet-backend
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - ./.env
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_DATA_MONGODB_DATABASE: ${SPRING_DATA_MONGODB_DATABASE}
      APP_CORS_ALLOWED_ORIGIN: "http://localhost:4200,http://127.0.0.1:4200"
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SECURITY_JWT_EXPIRATION_MS: ${SECURITY_JWT_EXPIRATION_MS}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: oportunidadescefet-frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    env_file:
      - ./.env
    environment:
      NG_ALLOWED_HOSTS: "localhost,127.0.0.1"
      FRONTEND_API_BASE_URL: "http://127.0.0.1:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
