version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo-oportunidades-cefet
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: oportunidades_cefet
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: oportunidadescefet-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongo:27017/oportunidades_cefet?authSource=admin
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: oportunidadescefet-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
