spring.application.name=Backend

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:secret@mongo:27017/oportunidades_cefet?authSource=admin}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:oportunidades_cefet}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}

security.jwt.secret=${SECURITY_JWT_SECRET:QmFja2VuZC1PcG9ydHVuaWRhZGVzLUNFRkVULURldi1TZWNyZXQtMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}
security.jwt.expiration-ms=${SECURITY_JWT_EXPIRATION_MS:86400000}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG